### PR TITLE
Update for Pandeia v1.5.2

### PR DESCRIPTION
**Pull request by ariedel**
This PR contains new notebooks and a revised Dockerfile and README for Pandeia Engine v1.5.2 (to be released 2020.08.31).

One specific question: Does WebbPSF 0.9.0 still rely on pysyphot? If so, it needs to be added back to the conda installation commands.

### CODE REVIEW

**Comment by ariedel** [comment]
I have reinstated pysynphot to the list of necessary packages.
I will merge this on October 5 if I haven't heard back from @robelgeda , seeing as whomever needs the latest roman packages has not been getting them.

**Comment by robelgeda** [comment]
Hi @ariedel, the changes to the docker file and the notebook seems fine to me. Admittedly the readme is now using Roman and WFIRST but I will work on changing it in October. So I am inclined to merge this now if someone needs the files and notebooks. Before you introduce this let me do a release or a tag so we can keep track of the original version of the code.

**Review by robelgeda — APPROVED** [review]
Changes look good, may be merged after the current version has been tagged.

**Comment by robelgeda** [comment]
I have released the code, you may merge this PR when appropriate.

**Comment by ariedel** [comment]
Thanks, Robel!

**Pull request merged**
